# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myImageImmersion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(default='empty', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
