# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myImageImmersion', '0002_auto_20171203_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.TextField()),
            ],
        ),
    ]
