# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myImageImmersion', '0003_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.ImageField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
